package org.dspace.dao.jena; 
import com.hp.hpl.jena.rdf.model.*;
 
/**
 * Vocabulary definitions from dspace.n3 
 * @author Auto-generated by schemagen on 30 Jun 2008 16:17 
 */
public class DSPACE {
    /** <p>The RDF model that holds the vocabulary terms</p> */
    private static Model m_model = ModelFactory.createDefaultModel();
    
    /** <p>The namespace of the vocabulary as a string</p> */
    public static final String NS = "http://purl.org/dspace/model#";
    
    /** <p>The namespace of the vocabulary as a string</p>
     *  @see #NS */
    public static String getURI() {return NS;}
    
    /** <p>The namespace of the vocabulary as a resource</p> */
    public static final Resource NAMESPACE = m_model.createResource( NS );
    
    /** <p>Administrator of this Collection.</p> */
    public static final Property admin = m_model.createProperty( "http://purl.org/dspace/model#admin" );
    
    /** <p>Known file extension for the given BitstreamFormat.</p> */
    public static final Property fileExtension = m_model.createProperty( "http://purl.org/dspace/model#fileExtension" );
    
    /** <p>Bitstream Property</p> */
    public static final Property hasBitstream = m_model.createProperty( "http://purl.org/dspace/model#hasBitstream" );
    
    /** <p>Bitstream Format Property</p> */
    public static final Property hasBitstreamFormat = m_model.createProperty( "http://purl.org/dspace/model#hasBitstreamFormat" );
    
    /** <p>Has DSpace Bundle</p> */
    public static final Property hasBundle = m_model.createProperty( "http://purl.org/dspace/model#hasBundle" );
    
    /** <p>Has Collection</p> */
    public static final Property hasCollection = m_model.createProperty( "http://purl.org/dspace/model#hasCollection" );
    
    /** <p>Has DSpace Community</p> */
    public static final Property hasCommunity = m_model.createProperty( "http://purl.org/dspace/model#hasCommunity" );
    
    /** <p>Has Item</p> */
    public static final Property hasItem = m_model.createProperty( "http://purl.org/dspace/model#hasItem" );
    
    /** <p>Has DSpace Group Member</p> */
    public static final Property hasMember = m_model.createProperty( "http://purl.org/dspace/model#hasMember" );
    
    /** <p>Has Sub-Community</p> */
    public static final Property hasSubCommunity = m_model.createProperty( "http://purl.org/dspace/model#hasSubCommunity" );
    
    /** <p>Has Sub-Group</p> */
    public static final Property hasSubGroup = m_model.createProperty( "http://purl.org/dspace/model#hasSubGroup" );
    
    /** <p>Part of Collection</p> */
    public static final Property isPartOfCollection = m_model.createProperty( "http://purl.org/dspace/model#isPartOfCollection" );
    
    /** <p>Is part of DSpace Community</p> */
    public static final Property isPartOfCommunity = m_model.createProperty( "http://purl.org/dspace/model#isPartOfCommunity" );
    
    /** <p>Part of DSpace Group</p> */
    public static final Property isPartOfGroup = m_model.createProperty( "http://purl.org/dspace/model#isPartOfGroup" );
    
    /** <p>Part of DSpace Item</p> */
    public static final Property isPartOfItem = m_model.createProperty( "http://purl.org/dspace/model#isPartOfItem" );
    
    /** <p>Is Part of DSpace Site</p> */
    public static final Property isPartOfSite = m_model.createProperty( "http://purl.org/dspace/model#isPartOfSite" );
    
    /** <p>The EPerson's Language.</p> */
    public static final Property language = m_model.createProperty( "http://purl.org/dspace/model#language" );
    
    /** <p>License for this Collection.</p> */
    public static final Property license = m_model.createProperty( "http://purl.org/dspace/model#license" );
    
    /** <p>A Community or Collection Logo</p> */
    public static final Property logo = m_model.createProperty( "http://purl.org/dspace/model#logo" );
    
    /** <p>Full Text Description of the Object (often contains HTML)</p> */
    public static final Property longDescription = m_model.createProperty( "http://purl.org/dspace/model#longDescription" );
    
    /** <p>MIME Type of the given BitstreamFormat.</p> */
    public static final Property mimeType = m_model.createProperty( "http://purl.org/dspace/model#mimeType" );
    
    /** <p>Submitter of this Item / Collection.</p> */
    public static final Property submitter = m_model.createProperty( "http://purl.org/dspace/model#submitter" );
    
    /** <p>Bitstream Format Support Level.</p> */
    public static final Property support = m_model.createProperty( "http://purl.org/dspace/model#support" );
    
    /** <p>Universally Unique Identifier for this object.</p> */
    public static final Property uuid = m_model.createProperty( "http://purl.org/dspace/model#uuid" );
    
    /** <p>A DSpace Bitstream</p> */
    public static final Resource Bitstream = m_model.createResource( "http://purl.org/dspace/model#Bitstream" );
    
    /** <p>A DSpace Bitstream Format</p> */
    public static final Resource BitstreamFormat = m_model.createResource( "http://purl.org/dspace/model#BitstreamFormat" );
    
    /** <p>A DSpace Bundle</p> */
    public static final Resource Bundle = m_model.createResource( "http://purl.org/dspace/model#Bundle" );
    
    /** <p>A DSpace Collection</p> */
    public static final Resource Collection = m_model.createResource( "http://purl.org/dspace/model#Collection" );
    
    /** <p>A DSpace Community</p> */
    public static final Resource Community = m_model.createResource( "http://purl.org/dspace/model#Community" );
    
    /** <p>DSpace Object is an abstract Class for any Specific DSpace Data Model Types.</p> */
    public static final Resource DSpaceObject = m_model.createResource( "http://purl.org/dspace/model#DSpaceObject" );
    
    /** <p>A DSpace EPerson</p> */
    public static final Resource EPerson = m_model.createResource( "http://purl.org/dspace/model#EPerson" );
    
    /** <p>A DSpace Group</p> */
    public static final Resource Group = m_model.createResource( "http://purl.org/dspace/model#Group" );
    
    /** <p>A DSpace Item</p> */
    public static final Resource Item = m_model.createResource( "http://purl.org/dspace/model#Item" );
    
    /** <p>A DSpace Policy</p> */
    public static final Resource Policy = m_model.createResource( "http://purl.org/dspace/model#Policy" );
    
    /** <p>A DSpace Site</p> */
    public static final Resource Site = m_model.createResource( "http://purl.org/dspace/model#Site" );
    
}
